export enum CHROME_STORAGE_KEY_ENUM {
  THEME = 'theme',
  TAB_ID = 'tab_id',
  TAB_URL = 'tab_url',
  HISTORY_URL = 'history_url',
  CURRENT_PERIOD = 'currentPeriod',
  PERIODS = 'periods',
  GOOGLE_AUTH_TOKEN = 'google_auth_token',
  GOOGLE_USER_INFO = 'google_user_info',
  USER_EMAIL = 'user_email',
  USER_ID = 'user_id',
  POMODORO_SETTINGS = 'pomodoro_settings',
  POMODORO_STATE = 'pomodoro_state',
  OPENED_FOLDERS = 'opened_folders',
  WEBSITES_LIBRARY = 'websites_library',
  CURRENT_ROUTE = 'current_route',
}

export type ChromeStorageKeyType =
  | CHROME_STORAGE_KEY_ENUM.PERIODS
  | CHROME_STORAGE_KEY_ENUM.CURRENT_PERIOD
  | CHROME_STORAGE_KEY_ENUM.THEME
  | CHROME_STORAGE_KEY_ENUM.TAB_ID
  | CHROME_STORAGE_KEY_ENUM.TAB_URL
  | CHROME_STORAGE_KEY_ENUM.HISTORY_URL
  | CHROME_STORAGE_KEY_ENUM.GOOGLE_AUTH_TOKEN
  | CHROME_STORAGE_KEY_ENUM.GOOGLE_USER_INFO
  | CHROME_STORAGE_KEY_ENUM.USER_EMAIL
  | CHROME_STORAGE_KEY_ENUM.USER_ID
  | CHROME_STORAGE_KEY_ENUM.POMODORO_SETTINGS
  | CHROME_STORAGE_KEY_ENUM.OPENED_FOLDERS
  | CHROME_STORAGE_KEY_ENUM.POMODORO_STATE
  | CHROME_STORAGE_KEY_ENUM.WEBSITES_LIBRARY
  | CHROME_STORAGE_KEY_ENUM.CURRENT_ROUTE;
