export enum CHROME_STORAGE_KEY_ENUM {
  THEME = 'theme',
  TAB_ID = 'tab_id',
  TAB_URL = 'tab_url',
  HISTORY_URL = 'history_url',
  CURRENT_PERIOD = 'currentPeriod',
  PERIODS = 'periods',
  ALL_BLOCKED_WEBSITES = 'allBlockedSites',
  GITHUB_ACCESS_TOKEN = 'github_access_token',
}

export type ChromeStorageKeyType =
  | CHROME_STORAGE_KEY_ENUM.PERIODS
  | CHROME_STORAGE_KEY_ENUM.CURRENT_PERIOD
  | CHROME_STORAGE_KEY_ENUM.ALL_BLOCKED_WEBSITES
  | CHROME_STORAGE_KEY_ENUM.THEME
  | CHROME_STORAGE_KEY_ENUM.TAB_ID
  | CHROME_STORAGE_KEY_ENUM.TAB_URL
  | CHROME_STORAGE_KEY_ENUM.HISTORY_URL
  | CHROME_STORAGE_KEY_ENUM.GITHUB_ACCESS_TOKEN;
