export enum CHROME_COMMAND_ENUM {
  ADD_PERIOD = 'addPeriod',
  REMOVE_PERIOD = 'removePeriod',
  UPDATE_PERIOD = 'updatePeriod',
  TOGGLE_BLOCKED_WEBSITE = 'toggleBlockedWebsite',
  START_FOCUS = 'startFocus',
  STOP_FOCUS = 'stopFocus',
  TOGGLE_FOCUS = 'toggleFocus',
  TOGGLE_QUICK_FOCUS = 'toggleQuickFocus',
  GET_ACTIVE_TAB = 'getActiveTab',
}

export type ChromeCommandType =
  | CHROME_COMMAND_ENUM.GET_ACTIVE_TAB
  | CHROME_COMMAND_ENUM.ADD_PERIOD
  | CHROME_COMMAND_ENUM.REMOVE_PERIOD
  | CHROME_COMMAND_ENUM.UPDATE_PERIOD
  | CHROME_COMMAND_ENUM.TOGGLE_BLOCKED_WEBSITE
  | CHROME_COMMAND_ENUM.START_FOCUS
  | CHROME_COMMAND_ENUM.STOP_FOCUS
  | CHROME_COMMAND_ENUM.TOGGLE_FOCUS
  | CHROME_COMMAND_ENUM.TOGGLE_QUICK_FOCUS;
