export enum CHROME_COMMAND_ENUM {
  ADD_PERIOD = 'addPeriod',
  REMOVE_PERIOD = 'removePeriod',
  UPDATE_PERIOD = 'updatePeriod',
  TOGGLE_BLOCKED_WEBSITE = 'toggleBlockedWebsite',
  START_FOCUS = 'startFocus',
  STOP_FOCUS = 'stopFocus',
  TOGGLE_FOCUS = 'toggleFocus',
  TOGGLE_QUICK_FOCUS = 'toggleQuickFocus',
  GET_ACTIVE_TAB = 'getActiveTab',
  SET_CURRENT_PERIOD = 'setCurrentPeriod',
  SYNC_USER_DATA = 'syncUserData',
  START_GOOGLE_AUTH = 'startGoogleAuth',
  LOGOUT_GOOGLE_AUTH = 'logoutGoogleAuth',
  CLOSE_TAB = 'closeTab',
  SHOW_BANNER = 'showBanner',
  HIDE_BANNER = 'hideBanner',
  START_POMODORO = 'startPomodoro',
  STOP_POMODORO = 'stopPomodoro',
  PAUSE_POMODORO = 'pausePomodoro',
  RESUME_POMODORO = 'resumePomodoro',
  RESET_POMODORO = 'resetPomodoro',
  SET_POMODORO_SETTINGS = 'setPomodoroSettings',
  SET_POMODORO_STATE = 'setPomodoroState',
  OPEN_SIDE_PANEL_APP = 'openSidePanel',
  OPEN_POPUP_APP = 'openPopupApp',
  ADD_FOLDER = 'addFolder',
  REMOVE_FOLDER = 'removeFolder',
  ADD_WEBSITE_TO_FOLDER = 'addWebsiteToFolder',
  REMOVE_WEBSITE = 'removeWebsite',
  MOVE_WEBSITE = 'moveWebsite',
  CLEAR_TRASH = 'clearTrash',
}

export type ChromeCommandType =
  | CHROME_COMMAND_ENUM.GET_ACTIVE_TAB
  | CHROME_COMMAND_ENUM.ADD_PERIOD
  | CHROME_COMMAND_ENUM.REMOVE_PERIOD
  | CHROME_COMMAND_ENUM.UPDATE_PERIOD
  | CHROME_COMMAND_ENUM.TOGGLE_BLOCKED_WEBSITE
  | CHROME_COMMAND_ENUM.START_FOCUS
  | CHROME_COMMAND_ENUM.STOP_FOCUS
  | CHROME_COMMAND_ENUM.TOGGLE_FOCUS
  | CHROME_COMMAND_ENUM.TOGGLE_QUICK_FOCUS
  | CHROME_COMMAND_ENUM.SET_CURRENT_PERIOD
  | CHROME_COMMAND_ENUM.SYNC_USER_DATA
  | CHROME_COMMAND_ENUM.START_GOOGLE_AUTH
  | CHROME_COMMAND_ENUM.LOGOUT_GOOGLE_AUTH
  | CHROME_COMMAND_ENUM.CLOSE_TAB
  | CHROME_COMMAND_ENUM.SHOW_BANNER
  | CHROME_COMMAND_ENUM.HIDE_BANNER
  | CHROME_COMMAND_ENUM.START_POMODORO
  | CHROME_COMMAND_ENUM.STOP_POMODORO
  | CHROME_COMMAND_ENUM.PAUSE_POMODORO
  | CHROME_COMMAND_ENUM.RESUME_POMODORO
  | CHROME_COMMAND_ENUM.SET_POMODORO_SETTINGS
  | CHROME_COMMAND_ENUM.SET_POMODORO_STATE
  | CHROME_COMMAND_ENUM.RESET_POMODORO
  | CHROME_COMMAND_ENUM.OPEN_SIDE_PANEL_APP
  | CHROME_COMMAND_ENUM.OPEN_POPUP_APP
  | CHROME_COMMAND_ENUM.ADD_FOLDER
  | CHROME_COMMAND_ENUM.REMOVE_FOLDER
  | CHROME_COMMAND_ENUM.ADD_WEBSITE_TO_FOLDER
  | CHROME_COMMAND_ENUM.REMOVE_WEBSITE;
