export enum FOCUS_ERROR_ENUM {
  PERIOD_NOT_SCHEDULED_TODAY = 'PERIOD_NOT_SCHEDULED_TODAY',
  NO_CURRENT_PERIOD_TO_TOGGLE = 'NO_CURRENT_PERIOD_TO_TOGGLE',
  FOCUS_ALREADY_INACTIVE = 'FOCUS_ALREADY_INACTIVE',
  PERIOD_NOT_FOUND = 'PERIOD_NOT_FOUND',
}

export type FocusErrorType =
  | FOCUS_ERROR_ENUM.PERIOD_NOT_SCHEDULED_TODAY
  | FOCUS_ERROR_ENUM.NO_CURRENT_PERIOD_TO_TOGGLE
  | FOCUS_ERROR_ENUM.FOCUS_ALREADY_INACTIVE
  | FOCUS_ERROR_ENUM.PERIOD_NOT_FOUND;
