export enum FOCUS_ERROR_ENUM {
  PERIOD_NOT_SCHEDULED_TODAY = 'PERIOD_NOT_SCHEDULED_TODAY',
  PERIOD_OUTSIDE_TIME_RANGE = 'PERIOD_OUTSIDE_TIME_RANGE',
  PERIOD_NOT_FOUND = 'PERIOD_NOT_FOUND',
  UNKNOWN_COMMAND = 'UNKNOWN_COMMAND',
  GENERIC_ERROR = 'GENERIC_ERROR',
}
