export enum PERMISSION_LVL_ENUM {
  READ_ONLY = 'READ_ONLY',
  RESTRICTED = 'RESTRICTED',
  FULL_ACCESS = 'FULL_ACCESS',
}

export type PermissionLvlType =
  | PERMISSION_LVL_ENUM.RESTRICTED
  | PERMISSION_LVL_ENUM.FULL_ACCESS
  | PERMISSION_LVL_ENUM.READ_ONLY;
