export enum PERMISSION_LVL_ENUM {
  READ_ONLY = 'READ_ONLY',
  RESTRICTED = 'RESTRICTED',
  USER = 'USER',
}

export type PermissionLvlType =
  | PERMISSION_LVL_ENUM.RESTRICTED
  | PERMISSION_LVL_ENUM.USER
  | PERMISSION_LVL_ENUM.READ_ONLY;
