export enum VIEW_ENUM {
  FOCUS = 0,
  MENU = 1,
  ADD_PERIOD = 2,
  POMODORO = 3,
  EDIT_PERIOD = 4,
  SIDE_PANEL = 5,
}

export type ViewType =
  | VIEW_ENUM.FOCUS
  | VIEW_ENUM.MENU
  | VIEW_ENUM.ADD_PERIOD
  | VIEW_ENUM.POMODORO
  | VIEW_ENUM.EDIT_PERIOD
  | VIEW_ENUM.SIDE_PANEL;
